travis:
  secure:
    BINSTAR_TOKEN: qDESSM8Rq30AAxOIuwsqaJc3sigkbb2ZoIxOeGxJWTyoCRP+W1Ac7Waw0aM60dE1DIFTsOAcD5eKgPEtCLf1k6IGvfF4TWAG23cTWRLZJWZyhQEFwDv82leteh2hpSQJC2e2BOqjLXuHXR63gbb9gb21To5QP2xdBpDGFPiEglRsF3rvSDX368Q707qea2ujtyyPvzPbwy/ipi8alK+TDRmKS5e3VIXcFcpANA9YnHCMYpUPLfD6aZzwmq18As83QWTPDjUp6h1hmqQzjtnXkZbqXRuZ76Zb7JhBaLr9a7xhOTeBg6Q8wa/4olfYRhoMATwlDgBPyI2R1XGNcgTtTq+JTroFByX3zbo/PCM1NrHzv8aPCgviCL7L8+Bt3JpIj+jV+2n/W9bo9sPGjyj4lJ3xad/dxYkedtrCauDzNB4cWH7oZLiJzo8LsO9t40Qis0quo1AaMB6crAnUK24ugFozNiqOuPdj10jzVMJxjWLdalrICnoZNq0YbR7kvJypnzHO1f7NZJkuKhjiHLUtnhKxA2fYtVrwaVGDDvi3ODG7QYztPTZL839Vg1Vlo8goPioXE/Q+bdVAV75suG5NDa+7Gyz9iXeRU5TGGmErXISxTSU+uadzJOWMmfknVOS8f2MQOuwwdaU6RK1ELmuPIEO7MOy14sENXoeuAt2DG9w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
